# 第二次练习
## Q1

In [1]:
import numpy as np
arr = np.arange(1, 13)
arr2 = arr.reshape(3, 4)
print(arr2)
print("ndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12


## Q2

In [18]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7, 4.8])
arr_int = arr.astype(np.int32)
print(arr)
print(arr.dtype.name)
print(arr_int)
print(arr_int.dtype.name)

[1.5 2.6 3.7 4.8]
float64
[1 2 3 4]
int32


## Q3

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
result = arr[:2, 1:3]
print(result)

[[2 3]
 [6 7]]


## Q4

In [20]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
print(arr[[0, 2, 4]])
print(arr[arr > 20])

[10 20 30]
[25 30 35]


## Q5

In [ ]:
import numpy as np
arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_a + arr_b
print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## Q6

In [5]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
result = x.dot(y)
sqrt_x = np.sqrt(x)
print("sqrt_x:", sqrt_x)
print("result:", result)

sqrt_x: [1. 2. 3. 4.]
result: 122


## Q7

In [3]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
new_arr = arr.transpose((1, 0, 2))
print("原数组：", arr)
print("转置后：", new_arr)
print("新数组形状：", new_arr.shape)

原数组： [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
转置后： [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
新数组形状： (3, 2, 4)


## Q8

In [5]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
result = np.where(arr_con, arr_x, arr_y)
print("result:", result)


result: [1 6 7]


## Q9

In [7]:
import numpy as np
arr = np.array([[6, 2, 7],
                [3, 6, 2],
                [4, 3, 2]])
print("均值：", arr.mean())
print("排序前：\n", arr)
arr.sort(axis=0)
print("排序后：\n", arr)


均值： 3.888888888888889
排序前：
 [[6 2 7]
 [3 6 2]
 [4 3 2]]
排序后：
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


## Q10

In [ ]:
import numpy as np
np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
result = A.dot(B)
print("A:\n", A)
print("B:\n", B)
print("A.dot(B):\n", result)


A:
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
B:
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
A.dot(B):
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
